server:
  port: 8888
spring:
  datasource:
    #    驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/robot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:




############# 代理相关 ######################
#地址
proxy:
  address: 127.0.0.1
  #端口
  prot: 31051

############## Pixiv #####################
#pixiv 曲奇
pixiv:
  cookie: __utmz=235335808.1667921412.6.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided); _fbp=fb.1.1664507419868.1862602951; _gcl_au=1.1.481618285.1664507656; a_type=0; b_type=1; c_type=24; device_token=03fc95c7c0e06f62eb967d8f84dfc6b2; p_ab_d_id=2039590838; p_ab_id=8; p_ab_id_2=7; privacy_policy_agreement=5; privacy_policy_notification=0; pt_60er4xix=uid=hFoX142kAZ8ahatf3utX/w&nid=1&vid=A4VHu75Cm7Fqcy1OfFpqQA&vn=1&pvn=1&sact=1667960215757&to_flag=0&pl=IZoRf4OCSv6aouL5bhDEAg*pt*1667960092467; tag_view_ranking=-RR2Rsko5M~2nSCQQsTc0~WqJ8j0AdVx~MnQk2KrTaG~Ikk8Watd0M~5OXRF8yfCA~XpQ4ZH7dmM~BQFWWhxtER~PGh9Qwfchx~g5QWNKvqWG~YF75pHGGsJ~JzbKqbNQRw~PjCCJkiD1-~MgCvx1Tr0K~OEfLPRhb4I~-g5xRar-5o~X1wsnjZiV4~sIiQpu87ZS~6RGIKaaoI0~vEwIx5JKyv~lGfGcfePHt~2wbHjR4kz3~4nHKycFnns~vwbZBw15pU~2-ZLcTJsOe~Lt-oEicbBr~CrFcrMFJzz~0Sds1vVNKR~SF27tOuLS4~40drnC0w2C~ixJ21_XZkb~tgP8r-gOe_~s1DI4r3R9d~i4Q_o7CyIB~_hSAdpN9rx~3WMR0mAYlN~Mll6Av0Rvx~4-_9de7LBH~Xq0AUR-upz~cpt_Nk5mjc~xCR2NgnI9z~dlfkwgDL8s~CRMYKjF-AY~gwZWjfYJz0~RTJMXD26Ak~2zE5ERppfi~rpFAkqMwRB~y8GNntYHsi~j0QoKstmJz~OIWp81xmT1~fn5nUXtjWI~IM8w4TyKT9~Mj8JOWqtax~Jmyuf6Ki0a~XHY_w__Yr8~gooMLQqB9a; _im_vid=01GE65Z76F7K3ENYBVEDBQ7X34; login_ever=yes; adr_id=zYtXz85f1oclsoyfl46UpNA5aYIv8QXmIoeTOOMGjaoXSxaF; first_visit_datetime_pc=2022-09-30+12:10:17; yuid_b=SQB1RUA; __utmv=235335808.|2=login ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=87893357=1^9=p_ab_id=8=1^10=p_ab_id_2=7=1^11=lang=zh=1; __utma=235335808.516395827.1664507419.1669702698.1670919481.14; __utmc=235335808; __utmt=1; __cf_bm=IX58EKqdDfY1hyr9ajt6t6O_K7AwMykWevMB3.a9EvU-1670919483-0-AbimtoE5S9Xr7NFSCKTTGrF0KVgErD5XbKmi4Izk0I7aGZkMXLDm7szONzSK+h3m4DkODuGc9+XsDF7WOiIuDClPjyM3kqHSUS6Mj7/Of5D2nO9g+KRR90tY+0Z0o8kzjIahD0TwDl5r1l9PGyvx9nTd454WOMqEpaH8lMNF+lzrcLS+xFBxVOwljlknpaY8w1jD7fTalMNiYtAl/ow6lI0=; _gid=GA1.2.183854377.1670919484; PHPSESSID=87893357_2VsKNE59KaPFpWRfnc36UDdU31eHZKEr; _ga_MZ1NL4PHH0=GS1.1.1670919487.4.1.1670919546.0.0.0; __utmb=235335808.2.10.1670919481; QSI_S_ZN_5hF4My7Ad6VNNAi=v:0:0; cto_bundle=G9HTzl81bkY1VHliJTJGaWxOdHVtU0h5MmVGamxtN3lRVkR2OGZ1bG1uZVIzNXhETDNpT1IlMkZxaEhUUXV6OG9CanZSUUduMkREeU1vVUM4eUUxeU5LVEh0TGJUR0JrQnRKV25kJTJGRGglMkJwNGsyV1N5WVk3RUVLRyUyQjNLNHAlMkJYbkF0eVdVaVlPcWZQRGIzeHRWNGFaV3pIUSUyQmt5OXRHQSUzRCUzRA; _ga_75BBYNYN9J=GS1.1.1670919482.14.1.1670919606.0.0.0; _ga=GA1.2.998634401.1664507419
