server:
  port: 8888
spring:
  datasource:
    #    驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/robot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  #循环依赖配置
  main:
    allow-circular-references: true




############# 代理相关 ######################
#地址
proxy:
  address: 127.0.0.1
  #端口
  prot: 4780

############## Pixiv #####################
#pixiv 曲奇
pixiv:
  cookie: first_visit_datetime_pc=2022-01-15+16:24:35; p_ab_id=6; p_ab_id_2=7; p_ab_d_id=725819484; yuid_b=QiR3KUY; privacy_policy_notification=0; a_type=0; b_type=1; login_ever=yes; __utmv=235335808.|2=login ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=47152070=1^9=p_ab_id=6=1^10=p_ab_id_2=7=1^11=lang=zh=1; __gads=ID=d61c29f38a3b87d4:T=1648879922:S=ALNI_MZ4IKbKKkPo3FaDXeWvOC7YFvMM4w; _td=2102af6b-a0ca-4893-8456-4b9b4e92114c; _ga_ZQEKG3EF2C=GS1.1.1648879919.1.1.1648880174.0; _fbp=fb.1.1664986318114.1564410217; __utmz=235335808.1665597581.5.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided); PHPSESSID=47152070_bsDIE6sN2DKFgDWFdryBx7gxGyhM3WkP; _ga_MZ1NL4PHH0=GS1.1.1665597583.1.0.1665597586.0.0.0; c_type=24; _im_vid=01GF6NMJCSXZYVX788RFRNM826; _im_uid.3929=b.c32a1656969b88c4; adr_id=3rcMaPF7rRtn5ZY9NZKOSAN779NmiD3rlA0GLWorxJ4gSN8Z; privacy_policy_agreement=5; __utma=235335808.293471611.1642231481.1668868406.1671308379.10; __utmc=235335808; __utmt=1; __cf_bm=Xk5SYCuvOQc7c1p.JkGdfAGxo81j027aU2k5eKMt8a8-1671308379-0-AddIAVPYvg6HKFUKW0VpviV+HzbF5RibzyNRimzUyRtVVfWHflO6b96+hD2VLRDI1grVwE1T/7bRvVBbpiT3UcqxqoVQlm+lRxf5bRXbdcO/8yDHcFbdtUEAVBD6vSenmk+wS313w0s2TYGfva2aPppkI8IO7INDL7eqh3LCT/1i7N4+og/nB4vA2+uoVtCFrMeBP1EQXIRAX+JeOkhwG6g=; _gid=GA1.2.1193028102.1671308381; QSI_S_ZN_5hF4My7Ad6VNNAi=v:0:0; _ga=GA1.2.293471611.1642231481; cto_bundle=Cdj9a19mMDVzaWsyWXJDeEppJTJGdWdqNFByZ3lvRTVhJTJCeUhyM0tET2VCcHZjeXNOQ29BQWtDNjRaSyUyRjBJJTJCYlFaQVl3TnI3T2pXYVU1VzhsVWFySTFWTnowbm9ySlRydmQydmxvNFBTRW5DOUx6MVlQTU5XN0NLaUN2TVdESXNjQTNuaDFTcmpvdEV5UGpGU0xvUEhoZmtwdFlNdyUzRCUzRA; __utmb=235335808.17.9.1671308503495; tag_view_ranking=2nSCQQsTc0~-RR2Rsko5M~Lt-oEicbBr~0xsDLqCEW6~gCB7z_XWkp~40drnC0w2C~rfaOhju5br~eVxus64GZU~MnQk2KrTaG~KvLrgXsati~5oPIfUbtd6~hJCNVjGbgT~zVxkx_g3rI~VI5zumpdp0~yElTikDQKv~TBaFSm-fCU~yOqOtdektt~KMpT0re7Sq~lRxin4V3-v~-B0wgi3Odg~WlelQm0jTC~MO67n2Zm2e~i83OPEGrYw~cpt_Nk5mjc~BU9SQkS-zU~y8GNntYHsi~MM6RXH_rlN~yqhVAkZ_Lh~qBVGbZbpq5~VLHcJniKob~8H_bi3nVqy~i4Q_o7CyIB~UNmUR27_Et~sl1zKlow2b~OEfLPRhb4I~Vv3BMezZX0~Tw5Eb131xi~pulAFAgyK9~8NpFhmNqI1~LpbCr9z3pl~-FDRXhaIRy~zyKU3Q5L4C~Xyw8zvsyR4~DfALfs4Jyc~UZT8LkxvSB~fc4SIASWnV~Nj9NtvOK3A~KN7uxuR89w~M2vKPRxAge~-icjNyCPig~m_0UhmzK28~2Ej0iLEGHw~w8ffkPoJ_S~nQ_3uwnEAK~jpIZPQ502H~jfcC9KzP1p~GlaPmO2CNB; _ga_75BBYNYN9J=GS1.1.1671308380.7.1.1671308632.0.0.0

############## Saucenao #####################
#Saucenao api的key
saucenao:
  key: 076f12ff342d1efb7c84078b9f5a1fd4b2af1d89
